---
name: Sys-Info
version: 0.69_01
author:
  - 'Burak Gursoy <burak@cpan.org>'
abstract: Fetch information from the host system
license: perl
resources:
  license: ~
requires:
  IO::File: 0
  Sys::Info::Base: 0.69_01
  Sys::Info::Driver::Unknown: 0.69_01
  Sys::Info::Driver::Windows: 0.69_01
  Test::More: 0.40
provides:
  Sys::Info:
    file: lib/Sys/Info.pm
    version: 0.69_01
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
