---
abstract: 'Fetch information from the host system'
author:
  - 'Burak Gursoy <burak@cpan.org>'
build_requires:
  Test::More: 0.40
  Test::Sys::Info: 0.20
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sys-Info
no_index:
  directory:
    - monolithic_version
    - builder
    - t
provides:
  Sys::Info:
    file: lib/Sys/Info.pm
    version: 0.78
requires:
  Sys::Info::Base: 0.78
  Sys::Info::Driver::OSX: 0.78
resources:
  license: http://dev.perl.org/licenses/
  repository: http://bitbucket.org/burak/cpan-sys-info/
version: 0.78
