#!/usr/bin/perl -w
use strict;
use vars qw(%PREREQ %RECOMMEND);
use lib 'lib';

# copy-paste from Sys::Info::Constants
BEGIN {
    if ( ! defined &OSID ) {
        my %OS = (
            MSWin32  => 'Windows',
            MSWin64  => 'Windows',
            linux    => 'Linux',
            #darwin   => 'MacOSX',
        );
        $OS{$_} = 'BSD' for qw( freebsd openbsd netbsd );
        my $ID = $OS{ $^O } || 'Unknown';
        *OSID = sub () { "$ID" }
    }
}

%PREREQ = (
   'IO::File'                   => 0,
   'Test::More'                 => '0.40',
   'Sys::Info::Base'            => '0.69_06',
   'Sys::Info::Driver::' . OSID => '0.69_05',
);

1;
